# Generated by Django 4.0 on 2021-12-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
    ]
